
/*******************************************************************************
* Copyright (c) 2012 Tecnalia Research and Innovation.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
* This file is a result of OWL 2 java transformation using EMF
* 
* Generated by SMOOL SDK Wizard
*******************************************************************************/ 
package SCOTTConsumer.model.smoolcore;
       
import org.smool.kpi.model.smart.IAbstractOntConcept;

/**
 * This class implements interface for the ontology concept AccelerometerInformation
 * including all its properties.
 * @author Genrated via EMF OWL to java transformation
 * @version 1.0
 */

public interface IAccelerometerInformation extends IAbstractOntConcept, IContinuousInformation{

   /*
 	* PROPERTIES: GETTERS AND SETTERS
 	*/
   
 	/**
 	* Sets the axisx property.
 	* @param axisx Double value
 	*/
 	public void setAxisx(Double axisx );

	/**
 	* Gets the axisx property.
 	* @return a Double value
	*/
 	public Double getAxisx();

 	/**
 	* Sets the axisy property.
 	* @param axisy Double value
 	*/
 	public void setAxisy(Double axisy );

	/**
 	* Gets the axisy property.
 	* @return a Double value
	*/
 	public Double getAxisy();

 	/**
 	* Sets the axisz property.
 	* @param axisz Double value
 	*/
 	public void setAxisz(Double axisz );

	/**
 	* Gets the axisz property.
 	* @return a Double value
	*/
 	public Double getAxisz();

 	/**
 	* Sets the dataID property.
 	* @param dataID String value
 	*/
 	public void setDataID(String dataID );

	/**
 	* Gets the dataID property.
 	* @return a String value
	*/
 	public String getDataID();

 	/**
 	* Sets the timestamp property.
 	* @param timestamp String value
 	*/
 	public void setTimestamp(String timestamp );

	/**
 	* Gets the timestamp property.
 	* @return a String value
	*/
 	public String getTimestamp();

 	/**
 	* Sets the unit property.
 	* @param unit String value
 	*/
 	public void setUnit(String unit );

	/**
 	* Gets the unit property.
 	* @return a String value
	*/
 	public String getUnit();
}
