
/*******************************************************************************
* Copyright (c) 2012 Tecnalia Research and Innovation.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
* This file is a result of OWL 2 java transformation using EMF
* 
* Generated by SMOOL SDK Wizard
*******************************************************************************/ 
package SCOTTProducer.model.smoolcore;
       
import org.smool.kpi.model.smart.IAbstractOntConcept;

/**
 * This class implements interface for the ontology concept HumidityInformation
 * including all its properties.
 * @author Genrated via EMF OWL to java transformation
 * @version 1.0
 */

public interface IHumidityInformation extends IAbstractOntConcept, IContinuousInformation{

   /*
 	* PROPERTIES: GETTERS AND SETTERS
 	*/
   
 	/**
 	* Sets the dataID property.
 	* @param dataID String value
 	*/
 	public void setDataID(String dataID );

	/**
 	* Gets the dataID property.
 	* @return a String value
	*/
 	public String getDataID();

 	/**
 	* Sets the humidityUnit property.
 	* @param humidityUnit String value
 	*/
 	public void setHumidityUnit(String humidityUnit );

	/**
 	* Gets the humidityUnit property.
 	* @return a String value
	*/
 	public String getHumidityUnit();

 	/**
 	* Sets the humidityValue property.
 	* @param humidityValue Double value
 	*/
 	public void setHumidityValue(Double humidityValue );

	/**
 	* Gets the humidityValue property.
 	* @return a Double value
	*/
 	public Double getHumidityValue();

 	/**
 	* Sets the timestamp property.
 	* @param timestamp String value
 	*/
 	public void setTimestamp(String timestamp );

	/**
 	* Gets the timestamp property.
 	* @return a String value
	*/
 	public String getTimestamp();

 	/**
 	* Sets the unit property.
 	* @param unit String value
 	*/
 	public void setUnit(String unit );

	/**
 	* Gets the unit property.
 	* @return a String value
	*/
 	public String getUnit();
}
