
/*******************************************************************************
* Copyright (c) 2012 Tecnalia Research and Innovation.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
* This file is a result of OWL 2 java transformation using EMF
* 
* Generated by SMOOL SDK Wizard
*******************************************************************************/ 
package SCOTTProducer.model.smoolcore;
       
import org.smool.kpi.model.smart.IAbstractOntConcept;

/**
 * This class implements interface for the ontology concept PreferenceInformation
 * including all its properties.
 * @author Genrated via EMF OWL to java transformation
 * @version 1.0
 */

public interface IPreferenceInformation extends IAbstractOntConcept, IDiscreteInformation{

   /*
 	* PROPERTIES: GETTERS AND SETTERS
 	*/
   
 	/**
 	* Sets the PreferredTemperature property.
 	* @param PreferredTemperature Integer value
 	*/
 	public void setPreferredTemperature(Integer PreferredTemperature );

	/**
 	* Gets the PreferredTemperature property.
 	* @return a Integer value
	*/
 	public Integer getPreferredTemperature();

 	/**
 	* Sets the dataID property.
 	* @param dataID String value
 	*/
 	public void setDataID(String dataID );

	/**
 	* Gets the dataID property.
 	* @return a String value
	*/
 	public String getDataID();

 	/**
 	* Sets the disabilityType property.
 	* @param disabilityType String value
 	*/
 	public void setDisabilityType(String disabilityType );

	/**
 	* Gets the disabilityType property.
 	* @return a String value
	*/
 	public String getDisabilityType();

 	/**
 	* Sets the isSmoker property.
 	* @param isSmoker Boolean value
 	*/
 	public void setIsSmoker(Boolean isSmoker );

	/**
 	* Gets the isSmoker property.
 	* @return a Boolean value
	*/
 	public Boolean getIsSmoker();

 	/**
 	* Sets the timestamp property.
 	* @param timestamp String value
 	*/
 	public void setTimestamp(String timestamp );

	/**
 	* Gets the timestamp property.
 	* @return a String value
	*/
 	public String getTimestamp();

 	/**
 	* Sets the userIDPublic property.
 	* @param userIDPublic String value
 	*/
 	public void setUserIDPublic(String userIDPublic );

	/**
 	* Gets the userIDPublic property.
 	* @return a String value
	*/
 	public String getUserIDPublic();
}
